### ISSUE TITLE
how to install package

### ISSUE THREAD

**Issue by an99990** [KanarekApp/flutter_map_fast_markers#5]
Hi i am new to flutter, and have been dealing with a lot of markers.
So i wanted to try your repo.
Is it possible to add the installation process in the README.
How do i import in a dart file ? and how i include it in the pubsec ?

Thank you

**Comment by an99990** [comment]
```
  flutter_map:
    git:
      url: "https://github.com/KanarekApp/flutter_map"
      ref: canary
  flutter_map_fast_markers:
    git:
      url: "https://github.com/KanarekApp/flutter_map_fast_markers.git"
      ref: canary
```
